default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        entry: bash -c 'isort --check-only .'
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
      - id: black
        entry: bash -c 'black --check .'
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: bash -c 'python3 -m flake8 .'
        stages: [commit]
