name: code-check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements/development.txt
      - run: isort --check-only .
      - run: black --check .
      - run: flake8 .
      - run: pytest --cov
